#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/chopin

PRODUCT_COPY_FILES += \
    vendor/xiaomi/chopin/proprietary/vendor/etc/audio_device.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_device.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/audio_param/AudioParamOptions.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/audio_param/AudioParamOptions_vext.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions_vext.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/audio_param/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_AudioParam.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/audio_param/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_AudioParam.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/audio_param/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_AudioParam.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/audio_param/PlaybackVolAna_CeRegion_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_CeRegion_AudioParam.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/audio_param/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_AudioParam.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/audio_param/PlaybackVolDigi_CeRegion_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_CeRegion_AudioParam.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/audio_param/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_AudioParam.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/audio_param/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/audio_param/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_AudioParam.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/audio_param/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_AudioParam.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/audio_param/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamUnitDesc.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/audio_param/RingbackVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_AudioParam.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/audio_param/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_AudioParam.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/audio_param/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_AudioParam.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/audio_param/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_AudioParam.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/audio_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_AudioParam.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/audio_param/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_AudioParam.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/audio_param/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_AudioParam.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/audio_param/VoWDspAec_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_AudioParam.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/audio_param/VoWVoiceCommand_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_AudioParam.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/aurisys_config_hifi3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_config_hifi3.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/aurisys_param/FV-SAM-MTKXX.dat:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_param/FV-SAM-MTKXX.dat \
    vendor/xiaomi/chopin/proprietary/vendor/etc/aurisys_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_param/Speech_AudioParam.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/CFR_para_HD.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_HD.bin \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/CFR_para_M.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_M.bin \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/CFR_para_T.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_T.bin \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/CFR_para_UW.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_UW.bin \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/CFR_para_W.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_W.bin \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/LDC_packdata_xiaomi_UW.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/LDC_packdata_xiaomi_UW.dat \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/ai_scene.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ai_scene.bin \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/almalence_sr_params_UW_upscale.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/almalence_sr_params_UW_upscale.config \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/almalence_sr_params_tele.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/almalence_sr_params_tele.config \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/almalence_sr_params_wide.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/almalence_sr_params_wide.config \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/apu_miai_capture.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/apu_miai_capture.bin \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/apu_miai_preview.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/apu_miai_preview.bin \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/com.xiaomi.dcal.wu.golden:$(TARGET_COPY_OUT_VENDOR)/etc/camera/com.xiaomi.dcal.wu.golden \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/deblur_sd_opencl_binary.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/deblur_sd_opencl_binary.bin \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/deblur_sd_opencl_params.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/deblur_sd_opencl_params.bin \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/intsense_config_optical_zoom.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/intsense_config_optical_zoom.bin \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/jiiganmodel/fusion_models/fusion_cache:$(TARGET_COPY_OUT_VENDOR)/etc/camera/jiiganmodel/fusion_models/fusion_cache \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/jiiganmodel/fusion_models/fusion_mecp.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/jiiganmodel/fusion_models/fusion_mecp.bin \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/jiiganmodel/fusion_models/fusion_model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/jiiganmodel/fusion_models/fusion_model \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/jiiganmodel/fusion_models/fusion_policy:$(TARGET_COPY_OUT_VENDOR)/etc/camera/jiiganmodel/fusion_models/fusion_policy \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/libal_fpc_tuning.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/libal_fpc_tuning.bin \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/reiddetv2.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/reiddetv2.bin \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/reiddetv2_apu_cache.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/reiddetv2_apu_cache.bin \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/reiddetv2_ocl_kernel.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/reiddetv2_ocl_kernel.bin \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/reiddetv2_ocl_param.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/reiddetv2_ocl_param.bin \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/sceneDetection.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sceneDetection.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/sr_params.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sr_params.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/video_bokeh_apu_front_20210413.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/video_bokeh_apu_front_20210413.bin \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/vidhance_calibration:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance_calibration \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/xiaomi/dualbokehsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/dualbokehsnapshot.json \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/xiaomi/frontbokehsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/frontbokehsnapshot.json \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/xiaomi/frontsinglesnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/frontsinglesnapshot.json \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/xiaomi/frontsupernightsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/frontsupernightsnapshot.json \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/xiaomi/manualsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/manualsnapshot.json \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/xiaomi/normalpreview.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/normalpreview.json \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/xiaomi/normalsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/normalsnapshot.json \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/xiaomi/satsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/satsnapshot.json \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/xiaomi/superhdsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/superhdsnapshot.json \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/xiaomi/superlowlightsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/superlowlightsnapshot.json \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/xiaomi/thirdpartysnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/thirdpartysnapshot.json \
    vendor/xiaomi/chopin/proprietary/vendor/etc/camera/xiaomi/uwsuperlowlightshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/uwsuperlowlightshot.json \
    vendor/xiaomi/chopin/proprietary/vendor/etc/cust_color_36_02_0a.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cust_color_36_02_0a.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/cust_color_42_02_0b.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cust_color_42_02_0b.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/cust_silky_brightness.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cust_silky_brightness.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/dsi_k10a_36_02_0a_dsc_vdo_mi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dsi_k10a_36_02_0a_dsc_vdo_mi.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/dsi_k10a_42_02_0b_dsc_vdo_mi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dsi_k10a_42_02_0b_dsc_vdo_mi.xml \
    vendor/xiaomi/chopin/proprietary/vendor/etc/init/camerahalserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camerahalserver.rc \
    vendor/xiaomi/chopin/proprietary/vendor/etc/misound_res.bin:$(TARGET_COPY_OUT_VENDOR)/etc/misound_res.bin \
    vendor/xiaomi/chopin/proprietary/vendor/etc/misound_res_headphone.bin:$(TARGET_COPY_OUT_VENDOR)/etc/misound_res_headphone.bin \
    vendor/xiaomi/chopin/proprietary/vendor/etc/misound_res_spk.bin:$(TARGET_COPY_OUT_VENDOR)/etc/misound_res_spk.bin \
    vendor/xiaomi/chopin/proprietary/vendor/etc/thermal-4k.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-4k.conf \
    vendor/xiaomi/chopin/proprietary/vendor/etc/thermal-camera.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-camera.conf \
    vendor/xiaomi/chopin/proprietary/vendor/etc/thermal-chg-only.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-chg-only.conf \
    vendor/xiaomi/chopin/proprietary/vendor/etc/thermal-class0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-class0.conf \
    vendor/xiaomi/chopin/proprietary/vendor/etc/thermal-map.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-map.conf \
    vendor/xiaomi/chopin/proprietary/vendor/etc/thermal-mgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-mgame.conf \
    vendor/xiaomi/chopin/proprietary/vendor/etc/thermal-navigation.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-navigation.conf \
    vendor/xiaomi/chopin/proprietary/vendor/etc/thermal-nolimits.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-nolimits.conf \
    vendor/xiaomi/chopin/proprietary/vendor/etc/thermal-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-normal.conf \
    vendor/xiaomi/chopin/proprietary/vendor/etc/thermal-per-camera.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-per-camera.conf \
    vendor/xiaomi/chopin/proprietary/vendor/etc/thermal-per-class0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-per-class0.conf \
    vendor/xiaomi/chopin/proprietary/vendor/etc/thermal-per-navigation.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-per-navigation.conf \
    vendor/xiaomi/chopin/proprietary/vendor/etc/thermal-per-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-per-normal.conf \
    vendor/xiaomi/chopin/proprietary/vendor/etc/thermal-per-video.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-per-video.conf \
    vendor/xiaomi/chopin/proprietary/vendor/etc/thermal-phone.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-phone.conf \
    vendor/xiaomi/chopin/proprietary/vendor/etc/thermal-tgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-tgame.conf \
    vendor/xiaomi/chopin/proprietary/vendor/etc/thermal-video.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-video.conf \
    vendor/xiaomi/chopin/proprietary/vendor/etc/thermald-devices.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermald-devices.conf \
    vendor/xiaomi/chopin/proprietary/vendor/firmware/NT36xxx_MP_Setting_Criteria_5950.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/NT36xxx_MP_Setting_Criteria_5950.csv \
    vendor/xiaomi/chopin/proprietary/vendor/firmware/NT36xxx_MP_Setting_Criteria_5952.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/NT36xxx_MP_Setting_Criteria_5952.csv \
    vendor/xiaomi/chopin/proprietary/vendor/firmware/RCV-cs35l41-dsp1-spk-cali.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RCV-cs35l41-dsp1-spk-cali.bin \
    vendor/xiaomi/chopin/proprietary/vendor/firmware/RCV-cs35l41-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RCV-cs35l41-dsp1-spk-prot.bin \
    vendor/xiaomi/chopin/proprietary/vendor/firmware/cs35l41-delta-rcv-handsfree.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-delta-rcv-handsfree.txt \
    vendor/xiaomi/chopin/proprietary/vendor/firmware/cs35l41-delta-rcv-music.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-delta-rcv-music.txt \
    vendor/xiaomi/chopin/proprietary/vendor/firmware/cs35l41-delta-spk-handsfree.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-delta-spk-handsfree.txt \
    vendor/xiaomi/chopin/proprietary/vendor/firmware/cs35l41-delta-spk-music.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-delta-spk-music.txt \
    vendor/xiaomi/chopin/proprietary/vendor/firmware/cs35l41-dsp1-spk-cali.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-cali.bin \
    vendor/xiaomi/chopin/proprietary/vendor/firmware/cs35l41-dsp1-spk-cali.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-cali.wmfw \
    vendor/xiaomi/chopin/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot.bin \
    vendor/xiaomi/chopin/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot.wmfw \
    vendor/xiaomi/chopin/proprietary/vendor/firmware/lib3a.ccu:$(TARGET_COPY_OUT_VENDOR)/firmware/lib3a.ccu \
    vendor/xiaomi/chopin/proprietary/vendor/firmware/novatek_nt36672c_k10a_fw01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_nt36672c_k10a_fw01.bin \
    vendor/xiaomi/chopin/proprietary/vendor/firmware/novatek_nt36672c_k10a_fw02.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_nt36672c_k10a_fw02.bin \
    vendor/xiaomi/chopin/proprietary/vendor/firmware/novatek_nt36672c_k10a_mp01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_nt36672c_k10a_mp01.bin \
    vendor/xiaomi/chopin/proprietary/vendor/firmware/novatek_nt36672c_k10a_mp02.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_nt36672c_k10a_mp02.bin \
    vendor/xiaomi/chopin/proprietary/vendor/firmware/novatek_ts_fw01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw01.bin \
    vendor/xiaomi/chopin/proprietary/vendor/firmware/novatek_ts_fw02.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw02.bin \
    vendor/xiaomi/chopin/proprietary/vendor/firmware/novatek_ts_mp01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_mp01.bin \
    vendor/xiaomi/chopin/proprietary/vendor/firmware/novatek_ts_mp02.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_mp02.bin \
    vendor/xiaomi/chopin/proprietary/vendor/thh/ta/8aaaf201246000007143fe4f7c823c80.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/8aaaf201246000007143fe4f7c823c80.ta

PRODUCT_PACKAGES += \
    audio.primary.mt6893 \
    libaudio_param_parser-vnd \
    libfvaudio \
    libmisound \
    libmisoundcrossfade \
    com.xiaomi.plugin.capbokeh \
    com.xiaomi.plugin.dc \
    com.xiaomi.plugin.depurple \
    com.xiaomi.plugin.hdr \
    com.xiaomi.plugin.ldc \
    com.xiaomi.plugin.memcpy \
    com.xiaomi.plugin.miaideblur \
    com.xiaomi.plugin.miaihdr \
    com.xiaomi.plugin.miaiie \
    com.xiaomi.plugin.mibokeh \
    com.xiaomi.plugin.mifragment \
    com.xiaomi.plugin.misegment \
    com.xiaomi.plugin.rawsuperlight \
    com.xiaomi.plugin.skinbeautifier \
    com.xiaomi.plugin.sr \
    com.xiaomi.plugin.superlowlight \
    com.xiaomi.plugin.supernight \
    com.xiaomi.plugin.swflip \
    com.xiaomi.plugin.tetrassr \
    com.xiaomi.plugin.uwfusion \
    gc02m1sunny_mipi_raw_IdxMgr \
    gc02m1sunny_mipi_raw_tuning \
    android.hardware.camera.provider@2.6-impl-mediatek \
    vendor.mediatek.hardware.camera.atms@1.0-impl \
    vendor.mediatek.hardware.camera.bgservice@1.1-impl \
    vendor.mediatek.hardware.camera.isphal@1.0-impl \
    vendor.mediatek.hardware.camera.lomoeffect@1.0-impl \
    imx355sunny_mipi_raw_IdxMgr \
    imx355sunny_mipi_raw_tuning \
    lib3a.ae.core \
    lib3a.ae \
    lib3a.ae.stat \
    lib3a.af.assist.models \
    lib3a.af.assist \
    lib3a.af.assist.utils \
    lib3a.af.core \
    lib3a.af \
    lib3a.aishutter.models \
    lib3a.alsflicker \
    lib3a.awb.core \
    lib3a.ccudrv \
    lib3a.ccuif \
    lib3a.custom.ae \
    lib3a.dce \
    lib3a.flash \
    lib3a.flicker \
    lib3a.gma \
    lib3a.lce \
    lib3a.log \
    lib3a.n3d3a \
    lib3a.sensors.color \
    lib3a.sensors.flicker \
    libCamera_gc02m1sunnymipiraw_E2EHDR_Preview \
    libCamera_gc02m1sunnymipiraw_E2EHDR_Video \
    libCamera_gc02m1sunnymipiraw_Face_Capture \
    libCamera_gc02m1sunnymipiraw_Flash_Capture \
    libCamera_gc02m1sunnymipiraw_HDR_Capture \
    libCamera_gc02m1sunnymipiraw_HDR_Preview \
    libCamera_gc02m1sunnymipiraw_HDR_Video \
    libCamera_gc02m1sunnymipiraw_N3D_Capture \
    libCamera_gc02m1sunnymipiraw_N3D_Preview \
    libCamera_gc02m1sunnymipiraw_N3D_Video \
    libCamera_gc02m1sunnymipiraw_P1_YUV \
    libCamera_gc02m1sunnymipiraw_Scene_Capture \
    libCamera_gc02m1sunnymipiraw_Scene_Capture_4cell \
    libCamera_gc02m1sunnymipiraw_Scene_Preview \
    libCamera_gc02m1sunnymipiraw_Scene_Preview_4k \
    libCamera_gc02m1sunnymipiraw_Scene_Preview_ZSD_Flash \
    libCamera_gc02m1sunnymipiraw_Video_1080 \
    libCamera_gc02m1sunnymipiraw_Video_4k \
    libCamera_gc02m1sunnymipiraw_Video_Zoom \
    libCamera_gc02m1sunnymipiraw_Zoom_Capture \
    libCamera_gc02m1sunnymipiraw_Zoom_Capture01 \
    libCamera_gc02m1sunnymipiraw_Zoom_Preview \
    libCamera_gc02m1sunnymipiraw_Zoom_Preview01 \
    libCamera_imx355sunnymipiraw_3rd_Capture \
    libCamera_imx355sunnymipiraw_3rd_Preview \
    libCamera_imx355sunnymipiraw_3rd_Video \
    libCamera_imx355sunnymipiraw_EIS_Video_1080P \
    libCamera_imx355sunnymipiraw_EIS_Video_1080P_Zoom1 \
    libCamera_imx355sunnymipiraw_EIS_Video_1080P_Zoom2 \
    libCamera_imx355sunnymipiraw_EIS_Video_720P \
    libCamera_imx355sunnymipiraw_EIS_Video_720P_Zoom1 \
    libCamera_imx355sunnymipiraw_EIS_Video_720P_Zoom2 \
    libCamera_imx355sunnymipiraw_Face_Capture \
    libCamera_imx355sunnymipiraw_Face_Preview \
    libCamera_imx355sunnymipiraw_Flash_Capture \
    libCamera_imx355sunnymipiraw_HDR_Face_Capture \
    libCamera_imx355sunnymipiraw_HDR_Scene_Capture \
    libCamera_imx355sunnymipiraw_HDR_Scene_Capture_Zoom1 \
    libCamera_imx355sunnymipiraw_HDR_Scene_Capture_Zoom2 \
    libCamera_imx355sunnymipiraw_LLHDR_Face_Capture \
    libCamera_imx355sunnymipiraw_LLHDR_Scene_Capture \
    libCamera_imx355sunnymipiraw_Professional_Capture \
    libCamera_imx355sunnymipiraw_Professional_Preview \
    libCamera_imx355sunnymipiraw_QQWechat_VideoCall \
    libCamera_imx355sunnymipiraw_Scene_Capture \
    libCamera_imx355sunnymipiraw_Scene_Capture_Zoom1 \
    libCamera_imx355sunnymipiraw_Scene_Capture_Zoom2 \
    libCamera_imx355sunnymipiraw_Scene_Preview \
    libCamera_imx355sunnymipiraw_Scene_Preview_Zoom1 \
    libCamera_imx355sunnymipiraw_Scene_Preview_Zoom2 \
    libCamera_imx355sunnymipiraw_SuperNightRaw_Capture \
    libCamera_imx355sunnymipiraw_SuperNightRaw_Preview \
    libCamera_imx355sunnymipiraw_Video_1080P \
    libCamera_imx355sunnymipiraw_Video_1080P_Zoom1 \
    libCamera_imx355sunnymipiraw_Video_1080P_Zoom2 \
    libCamera_imx355sunnymipiraw_Video_720P \
    libCamera_imx355sunnymipiraw_Video_720P_Zoom1 \
    libCamera_imx355sunnymipiraw_Video_720P_Zoom2 \
    libCamera_ov16a1qofilmmipiraw_3rd_Capture \
    libCamera_ov16a1qofilmmipiraw_3rd_Preview \
    libCamera_ov16a1qofilmmipiraw_3rd_Video \
    libCamera_ov16a1qofilmmipiraw_FaceUnlock_Capture \
    libCamera_ov16a1qofilmmipiraw_Face_Capture \
    libCamera_ov16a1qofilmmipiraw_FrontLight_Capture \
    libCamera_ov16a1qofilmmipiraw_FrontLight_Preview \
    libCamera_ov16a1qofilmmipiraw_HDR_Capture \
    libCamera_ov16a1qofilmmipiraw_Panorama_Capture \
    libCamera_ov16a1qofilmmipiraw_Portrait_Capture \
    libCamera_ov16a1qofilmmipiraw_Portrait_Preview \
    libCamera_ov16a1qofilmmipiraw_QQWeChat_Preview \
    libCamera_ov16a1qofilmmipiraw_QQWechat_Video \
    libCamera_ov16a1qofilmmipiraw_QQWechat_VideoCall \
    libCamera_ov16a1qofilmmipiraw_Scene_Capture \
    libCamera_ov16a1qofilmmipiraw_Scene_Preview \
    libCamera_ov16a1qofilmmipiraw_Short_Video \
    libCamera_ov16a1qofilmmipiraw_SuperNightLight_Capture \
    libCamera_ov16a1qofilmmipiraw_SuperNightLight_Preview \
    libCamera_ov16a1qofilmmipiraw_SuperNight_Capture \
    libCamera_ov16a1qofilmmipiraw_SuperNight_Preview \
    libCamera_ov16a1qofilmmipiraw_VideoHDR_1080P \
    libCamera_ov16a1qofilmmipiraw_VideoHDR_1080P_Reconfig \
    libCamera_ov16a1qofilmmipiraw_VideoHDR_720P \
    libCamera_ov16a1qofilmmipiraw_VideoHDR_720P_Reconfig \
    libCamera_ov16a1qofilmmipiraw_Video_1080P \
    libCamera_ov16a1qofilmmipiraw_Video_1080P_EIS \
    libCamera_ov16a1qofilmmipiraw_Video_720P \
    libCamera_ov16a1qofilmmipiraw_Video_720P_120fps \
    libCamera_ov16a1qofilmmipiraw_Video_720P_EIS \
    libCamera_ov64b40sunnymipiraw1_3rd_Capture \
    libCamera_ov64b40sunnymipiraw1_3rd_Capture_1080P \
    libCamera_ov64b40sunnymipiraw1_AIShutter_Capture \
    libCamera_ov64b40sunnymipiraw1_AIShutter_Preview \
    libCamera_ov64b40sunnymipiraw1_Face_Capture \
    libCamera_ov64b40sunnymipiraw1_Face_Capture_64M \
    libCamera_ov64b40sunnymipiraw1_Face_Capture_CE \
    libCamera_ov64b40sunnymipiraw1_Face_Preview \
    libCamera_ov64b40sunnymipiraw1_Flash_A_Capture \
    libCamera_ov64b40sunnymipiraw1_Flash_A_Preview \
    libCamera_ov64b40sunnymipiraw1_Flash_A_Preview_zoom1 \
    libCamera_ov64b40sunnymipiraw1_HDR_Face_Capture \
    libCamera_ov64b40sunnymipiraw1_HDR_Scene_Capture \
    libCamera_ov64b40sunnymipiraw1_HDR_Scene_Capture_Zoom1 \
    libCamera_ov64b40sunnymipiraw1_HDR_Scene_Capture_Zoom2 \
    libCamera_ov64b40sunnymipiraw1_LLHDR_Face_Capture \
    libCamera_ov64b40sunnymipiraw1_LLHDR_Scene_Capture \
    libCamera_ov64b40sunnymipiraw1_Panorama_Capture \
    libCamera_ov64b40sunnymipiraw1_QQ_Preview \
    libCamera_ov64b40sunnymipiraw1_Scene_Capture \
    libCamera_ov64b40sunnymipiraw1_Scene_Capture_64M \
    libCamera_ov64b40sunnymipiraw1_Scene_Capture_CE \
    libCamera_ov64b40sunnymipiraw1_Scene_Capture_Magic \
    libCamera_ov64b40sunnymipiraw1_Scene_Capture_Professional \
    libCamera_ov64b40sunnymipiraw1_Scene_Capture_Zoom1 \
    libCamera_ov64b40sunnymipiraw1_Scene_Capture_Zoom2 \
    libCamera_ov64b40sunnymipiraw1_Scene_Preview \
    libCamera_ov64b40sunnymipiraw1_Scene_Preview_Zoom1 \
    libCamera_ov64b40sunnymipiraw1_Scene_Preview_Zoom2 \
    libCamera_ov64b40sunnymipiraw1_Scene_Professional_Preview \
    libCamera_ov64b40sunnymipiraw1_SuperNightRaw_Capture \
    libCamera_ov64b40sunnymipiraw1_SuperNightRaw_Preview \
    libCamera_ov64b40sunnymipiraw1_SuperNightSE_Capture \
    libCamera_ov64b40sunnymipiraw1_Video_1080P \
    libCamera_ov64b40sunnymipiraw1_Video_1080P_60fps \
    libCamera_ov64b40sunnymipiraw1_Video_1080P_60fps_EIS \
    libCamera_ov64b40sunnymipiraw1_Video_1080P_60fps_Zoom1 \
    libCamera_ov64b40sunnymipiraw1_Video_1080P_60fps_Zoom2 \
    libCamera_ov64b40sunnymipiraw1_Video_1080P_EIS \
    libCamera_ov64b40sunnymipiraw1_Video_1080P_EIS_Zoom1 \
    libCamera_ov64b40sunnymipiraw1_Video_1080P_EIS_Zoom2 \
    libCamera_ov64b40sunnymipiraw1_Video_1080P_Zoom1 \
    libCamera_ov64b40sunnymipiraw1_Video_1080P_Zoom2 \
    libCamera_ov64b40sunnymipiraw1_Video_4k \
    libCamera_ov64b40sunnymipiraw1_Video_4k_EIS \
    libCamera_ov64b40sunnymipiraw1_Video_4k_EIS_Zoom1 \
    libCamera_ov64b40sunnymipiraw1_Video_4k_EIS_Zoom2 \
    libCamera_ov64b40sunnymipiraw1_Video_4k_Zoom1 \
    libCamera_ov64b40sunnymipiraw1_Video_4k_Zoom2 \
    libCamera_ov64b40sunnymipiraw1_Video_720P \
    libCamera_ov64b40sunnymipiraw1_Video_720P_120fps \
    libCamera_ov64b40sunnymipiraw1_Video_720P_120fps_Zoom1 \
    libCamera_ov64b40sunnymipiraw1_Video_720P_120fps_Zoom2 \
    libCamera_ov64b40sunnymipiraw1_Video_720P_240fps \
    libCamera_ov64b40sunnymipiraw1_Video_720P_240fps_Zoom1 \
    libCamera_ov64b40sunnymipiraw1_Video_720P_240fps_Zoom2 \
    libCamera_ov64b40sunnymipiraw1_Video_720P_EIS \
    libCamera_ov64b40sunnymipiraw1_Video_720P_EIS_Zoom1 \
    libCamera_ov64b40sunnymipiraw1_Video_720P_EIS_Zoom2 \
    libCamera_ov64b40sunnymipiraw1_Video_720P_Zoom1 \
    libCamera_ov64b40sunnymipiraw1_Video_720P_Zoom2 \
    libCamera_ov64b40sunnymipiraw1_Video_Capture \
    libCamera_ov64b40sunnymipiraw1_Video_Enhance_1080P \
    libCamera_ov64b40sunnymipiraw1_Video_Enhance_1080P_EIS \
    libCamera_ov64b40sunnymipiraw1_Video_Enhance_1080P_Reconfig \
    libCamera_ov64b40sunnymipiraw1_Video_Enhance_1080P_Zoom1 \
    libCamera_ov64b40sunnymipiraw1_Video_Enhance_1080P_Zoom2 \
    libCamera_ov64b40sunnymipiraw1_Video_Enhance_4K \
    libCamera_ov64b40sunnymipiraw1_Video_Enhance_4K_Zoom1 \
    libCamera_ov64b40sunnymipiraw1_Video_Enhance_4K_Zoom2 \
    libCamera_ov64b40sunnymipiraw1_Video_Enhance_720P \
    libCamera_ov64b40sunnymipiraw1_Video_Enhance_720P_EIS \
    libCamera_ov64b40sunnymipiraw1_Video_Enhance_720P_Zoom1 \
    libCamera_ov64b40sunnymipiraw1_Video_Enhance_720P_Zoom2 \
    libCamera_ov64b40sunnymipiraw1_Video_Log \
    libCamera_ov64b40sunnymipiraw1_WeChatQQ_Video \
    libCamera_ov64b40sunnymipiraw1_WeChat_Preview \
    libCamera_ov64b40sunnymipiraw1_XTS_Capture \
    libCamera_ov64b40sunnymipiraw1_portrait_capture_full \
    libCamera_ov64b40sunnymipiraw1_portrait_preview_full \
    libCamera_ov64b40sunnymipiraw2_3rd_Capture \
    libCamera_ov64b40sunnymipiraw2_3rd_Capture_1080P \
    libCamera_ov64b40sunnymipiraw2_AIShutter_Capture \
    libCamera_ov64b40sunnymipiraw2_AIShutter_Preview \
    libCamera_ov64b40sunnymipiraw2_Face_Capture \
    libCamera_ov64b40sunnymipiraw2_Face_Capture_64M \
    libCamera_ov64b40sunnymipiraw2_Face_Capture_CE \
    libCamera_ov64b40sunnymipiraw2_Face_Preview \
    libCamera_ov64b40sunnymipiraw2_Flash_A_Capture \
    libCamera_ov64b40sunnymipiraw2_Flash_A_Preview \
    libCamera_ov64b40sunnymipiraw2_Flash_A_Preview_zoom1 \
    libCamera_ov64b40sunnymipiraw2_HDR_Face_Capture \
    libCamera_ov64b40sunnymipiraw2_HDR_Scene_Capture \
    libCamera_ov64b40sunnymipiraw2_HDR_Scene_Capture_Zoom1 \
    libCamera_ov64b40sunnymipiraw2_HDR_Scene_Capture_Zoom2 \
    libCamera_ov64b40sunnymipiraw2_LLHDR_Face_Capture \
    libCamera_ov64b40sunnymipiraw2_LLHDR_Scene_Capture \
    libCamera_ov64b40sunnymipiraw2_Panorama_Capture \
    libCamera_ov64b40sunnymipiraw2_QQ_Preview \
    libCamera_ov64b40sunnymipiraw2_Scene_Capture \
    libCamera_ov64b40sunnymipiraw2_Scene_Capture_64M \
    libCamera_ov64b40sunnymipiraw2_Scene_Capture_CE \
    libCamera_ov64b40sunnymipiraw2_Scene_Capture_Magic \
    libCamera_ov64b40sunnymipiraw2_Scene_Capture_Professional \
    libCamera_ov64b40sunnymipiraw2_Scene_Capture_Zoom1 \
    libCamera_ov64b40sunnymipiraw2_Scene_Capture_Zoom2 \
    libCamera_ov64b40sunnymipiraw2_Scene_Preview \
    libCamera_ov64b40sunnymipiraw2_Scene_Preview_Zoom1 \
    libCamera_ov64b40sunnymipiraw2_Scene_Preview_Zoom2 \
    libCamera_ov64b40sunnymipiraw2_Scene_Professional_Preview \
    libCamera_ov64b40sunnymipiraw2_SuperNightRaw_Capture \
    libCamera_ov64b40sunnymipiraw2_SuperNightRaw_Preview \
    libCamera_ov64b40sunnymipiraw2_SuperNightSE_Capture \
    libCamera_ov64b40sunnymipiraw2_Video_1080P \
    libCamera_ov64b40sunnymipiraw2_Video_1080P_60fps \
    libCamera_ov64b40sunnymipiraw2_Video_1080P_60fps_EIS \
    libCamera_ov64b40sunnymipiraw2_Video_1080P_60fps_Zoom1 \
    libCamera_ov64b40sunnymipiraw2_Video_1080P_60fps_Zoom2 \
    libCamera_ov64b40sunnymipiraw2_Video_1080P_EIS \
    libCamera_ov64b40sunnymipiraw2_Video_1080P_EIS_Zoom1 \
    libCamera_ov64b40sunnymipiraw2_Video_1080P_EIS_Zoom2 \
    libCamera_ov64b40sunnymipiraw2_Video_1080P_Zoom1 \
    libCamera_ov64b40sunnymipiraw2_Video_1080P_Zoom2 \
    libCamera_ov64b40sunnymipiraw2_Video_4k \
    libCamera_ov64b40sunnymipiraw2_Video_4k_EIS \
    libCamera_ov64b40sunnymipiraw2_Video_4k_EIS_Zoom1 \
    libCamera_ov64b40sunnymipiraw2_Video_4k_EIS_Zoom2 \
    libCamera_ov64b40sunnymipiraw2_Video_4k_Zoom1 \
    libCamera_ov64b40sunnymipiraw2_Video_4k_Zoom2 \
    libCamera_ov64b40sunnymipiraw2_Video_720P \
    libCamera_ov64b40sunnymipiraw2_Video_720P_120fps \
    libCamera_ov64b40sunnymipiraw2_Video_720P_120fps_Zoom1 \
    libCamera_ov64b40sunnymipiraw2_Video_720P_120fps_Zoom2 \
    libCamera_ov64b40sunnymipiraw2_Video_720P_240fps \
    libCamera_ov64b40sunnymipiraw2_Video_720P_240fps_Zoom1 \
    libCamera_ov64b40sunnymipiraw2_Video_720P_240fps_Zoom2 \
    libCamera_ov64b40sunnymipiraw2_Video_720P_EIS \
    libCamera_ov64b40sunnymipiraw2_Video_720P_EIS_Zoom1 \
    libCamera_ov64b40sunnymipiraw2_Video_720P_EIS_Zoom2 \
    libCamera_ov64b40sunnymipiraw2_Video_720P_Zoom1 \
    libCamera_ov64b40sunnymipiraw2_Video_720P_Zoom2 \
    libCamera_ov64b40sunnymipiraw2_Video_Capture \
    libCamera_ov64b40sunnymipiraw2_Video_Enhance_1080P \
    libCamera_ov64b40sunnymipiraw2_Video_Enhance_1080P_EIS \
    libCamera_ov64b40sunnymipiraw2_Video_Enhance_1080P_Reconfig \
    libCamera_ov64b40sunnymipiraw2_Video_Enhance_1080P_Zoom1 \
    libCamera_ov64b40sunnymipiraw2_Video_Enhance_1080P_Zoom2 \
    libCamera_ov64b40sunnymipiraw2_Video_Enhance_4K \
    libCamera_ov64b40sunnymipiraw2_Video_Enhance_4K_Zoom1 \
    libCamera_ov64b40sunnymipiraw2_Video_Enhance_4K_Zoom2 \
    libCamera_ov64b40sunnymipiraw2_Video_Enhance_720P \
    libCamera_ov64b40sunnymipiraw2_Video_Enhance_720P_EIS \
    libCamera_ov64b40sunnymipiraw2_Video_Enhance_720P_Zoom1 \
    libCamera_ov64b40sunnymipiraw2_Video_Enhance_720P_Zoom2 \
    libCamera_ov64b40sunnymipiraw2_Video_Log \
    libCamera_ov64b40sunnymipiraw2_WeChatQQ_Video \
    libCamera_ov64b40sunnymipiraw2_WeChat_Preview \
    libCamera_ov64b40sunnymipiraw2_XTS_Capture \
    libCamera_ov64b40sunnymipiraw2_portrait_capture_full \
    libCamera_ov64b40sunnymipiraw2_portrait_preview_full \
    libCamera_ov64b40sunnymipiraw_3rd_Capture \
    libCamera_ov64b40sunnymipiraw_3rd_Capture_1080P \
    libCamera_ov64b40sunnymipiraw_AIShutter_Capture \
    libCamera_ov64b40sunnymipiraw_AIShutter_Preview \
    libCamera_ov64b40sunnymipiraw_Face_Capture \
    libCamera_ov64b40sunnymipiraw_Face_Capture_64M \
    libCamera_ov64b40sunnymipiraw_Face_Capture_CE \
    libCamera_ov64b40sunnymipiraw_Face_Capture_Upscale \
    libCamera_ov64b40sunnymipiraw_Face_Preview \
    libCamera_ov64b40sunnymipiraw_Flash_A_Capture \
    libCamera_ov64b40sunnymipiraw_Flash_A_Preview \
    libCamera_ov64b40sunnymipiraw_Flash_A_Preview_zoom1 \
    libCamera_ov64b40sunnymipiraw_HDR_Face_Capture \
    libCamera_ov64b40sunnymipiraw_HDR_Scene_Capture \
    libCamera_ov64b40sunnymipiraw_HDR_Scene_Capture_Zoom1 \
    libCamera_ov64b40sunnymipiraw_HDR_Scene_Capture_Zoom2 \
    libCamera_ov64b40sunnymipiraw_LLHDR_Face_Capture \
    libCamera_ov64b40sunnymipiraw_LLHDR_Scene_Capture \
    libCamera_ov64b40sunnymipiraw_Panorama_Capture \
    libCamera_ov64b40sunnymipiraw_QQ_Preview \
    libCamera_ov64b40sunnymipiraw_Scene_Capture \
    libCamera_ov64b40sunnymipiraw_Scene_Capture_64M \
    libCamera_ov64b40sunnymipiraw_Scene_Capture_CE \
    libCamera_ov64b40sunnymipiraw_Scene_Capture_Magic \
    libCamera_ov64b40sunnymipiraw_Scene_Capture_Professional \
    libCamera_ov64b40sunnymipiraw_Scene_Capture_Upscale \
    libCamera_ov64b40sunnymipiraw_Scene_Capture_Zoom1 \
    libCamera_ov64b40sunnymipiraw_Scene_Capture_Zoom2 \
    libCamera_ov64b40sunnymipiraw_Scene_Preview \
    libCamera_ov64b40sunnymipiraw_Scene_Preview_Zoom1 \
    libCamera_ov64b40sunnymipiraw_Scene_Preview_Zoom2 \
    libCamera_ov64b40sunnymipiraw_Scene_Professional_Preview \
    libCamera_ov64b40sunnymipiraw_SuperNightRaw_Capture \
    libCamera_ov64b40sunnymipiraw_SuperNightRaw_Preview \
    libCamera_ov64b40sunnymipiraw_SuperNightSE_Capture \
    libCamera_ov64b40sunnymipiraw_Video_1080P \
    libCamera_ov64b40sunnymipiraw_Video_1080P_60fps \
    libCamera_ov64b40sunnymipiraw_Video_1080P_60fps_EIS \
    libCamera_ov64b40sunnymipiraw_Video_1080P_60fps_Zoom1 \
    libCamera_ov64b40sunnymipiraw_Video_1080P_60fps_Zoom2 \
    libCamera_ov64b40sunnymipiraw_Video_1080P_EIS \
    libCamera_ov64b40sunnymipiraw_Video_1080P_EIS_Zoom1 \
    libCamera_ov64b40sunnymipiraw_Video_1080P_EIS_Zoom2 \
    libCamera_ov64b40sunnymipiraw_Video_1080P_Zoom1 \
    libCamera_ov64b40sunnymipiraw_Video_1080P_Zoom2 \
    libCamera_ov64b40sunnymipiraw_Video_4k \
    libCamera_ov64b40sunnymipiraw_Video_4k_EIS \
    libCamera_ov64b40sunnymipiraw_Video_4k_EIS_Zoom1 \
    libCamera_ov64b40sunnymipiraw_Video_4k_EIS_Zoom2 \
    libCamera_ov64b40sunnymipiraw_Video_4k_Zoom1 \
    libCamera_ov64b40sunnymipiraw_Video_4k_Zoom2 \
    libCamera_ov64b40sunnymipiraw_Video_720P \
    libCamera_ov64b40sunnymipiraw_Video_720P_120fps \
    libCamera_ov64b40sunnymipiraw_Video_720P_120fps_Zoom1 \
    libCamera_ov64b40sunnymipiraw_Video_720P_120fps_Zoom2 \
    libCamera_ov64b40sunnymipiraw_Video_720P_240fps \
    libCamera_ov64b40sunnymipiraw_Video_720P_240fps_Zoom1 \
    libCamera_ov64b40sunnymipiraw_Video_720P_240fps_Zoom2 \
    libCamera_ov64b40sunnymipiraw_Video_720P_EIS \
    libCamera_ov64b40sunnymipiraw_Video_720P_EIS_Zoom1 \
    libCamera_ov64b40sunnymipiraw_Video_720P_EIS_Zoom2 \
    libCamera_ov64b40sunnymipiraw_Video_720P_Zoom1 \
    libCamera_ov64b40sunnymipiraw_Video_720P_Zoom2 \
    libCamera_ov64b40sunnymipiraw_Video_Capture \
    libCamera_ov64b40sunnymipiraw_Video_Enhance_1080P \
    libCamera_ov64b40sunnymipiraw_Video_Enhance_1080P_EIS \
    libCamera_ov64b40sunnymipiraw_Video_Enhance_1080P_Reconfig \
    libCamera_ov64b40sunnymipiraw_Video_Enhance_1080P_Zoom1 \
    libCamera_ov64b40sunnymipiraw_Video_Enhance_1080P_Zoom2 \
    libCamera_ov64b40sunnymipiraw_Video_Enhance_4K \
    libCamera_ov64b40sunnymipiraw_Video_Enhance_4K_Zoom1 \
    libCamera_ov64b40sunnymipiraw_Video_Enhance_4K_Zoom2 \
    libCamera_ov64b40sunnymipiraw_Video_Enhance_720P \
    libCamera_ov64b40sunnymipiraw_Video_Enhance_720P_EIS \
    libCamera_ov64b40sunnymipiraw_Video_Enhance_720P_Zoom1 \
    libCamera_ov64b40sunnymipiraw_Video_Enhance_720P_Zoom2 \
    libCamera_ov64b40sunnymipiraw_Video_Log \
    libCamera_ov64b40sunnymipiraw_WeChatQQ_Video \
    libCamera_ov64b40sunnymipiraw_WeChat_Preview \
    libCamera_ov64b40sunnymipiraw_XTS_Capture \
    libCamera_ov64b40sunnymipiraw_portrait_capture_full \
    libCamera_ov64b40sunnymipiraw_portrait_preview_full \
    libHalSuperSensorServer \
    libHalSuperSensorServerCWrapper \
    libSQLiteModule_VER_ALL \
    libSonyIMX230PdafLibrary \
    libSonyIMX230PdafLibraryWrapper \
    libSonyIMX338PdafLibrary \
    libSonyIMX338PdafLibraryWrapper \
    libSonyIMX386PdafLibrary \
    libSonyIMX386PdafLibraryWrapper \
    libSonyIMX519PdafLibrary \
    libSonyIMX519PdafLibraryWrapper \
    libSuperSensor \
    libSuperSensorCPU \
    libSuperSensorProcessor \
    lib_bsscore \
    lib_sr_models \
    libaaa_ltm \
    libaaa_ltmx \
    libaiawb_moon \
    libaiawb_moon_model \
    libaiawb_p1ggm \
    libaiawb_sun \
    libaiawb_sun_model \
    libaibc_tuning \
    libaibc_tuning_p2 \
    libaibc_tuning_p3 \
    libainrcore \
    libalCFR \
    libalLDC \
    libalhLDC \
    libanc_calibration_parser \
    libanc_dc_base \
    libarcsoft_beautyshot \
    libarcsoft_distortion_correction \
    libarcsoft_dualcam_refocus \
    libarcsoft_hdr_detection \
    libarcsoft_high_dynamic_range \
    libarcsoft_low_light_hdr \
    libarcsoft_portrait_lighting \
    libarcsoft_portrait_lighting_c \
    libarcsoft_sn_mtk_apu \
    libarcsoft_super_night_raw \
    libarcsoft_supernight \
    libbeauty_face_interface \
    libc++_shared \
    libcam.ArcCamEngine \
    libcam.afhal \
    libcam.chdr \
    libcam.feature_utils \
    libcam.hal3a.cctsvr \
    libcam.hal3a.log \
    libcam.hal3a.v3.ae \
    libcam.hal3a.v3.ai3a \
    libcam.hal3a.v3.awb \
    libcam.hal3a.v3.dng \
    libcam.hal3a.v3.fsmgr \
    libcam.hal3a.v3.lscMgr \
    libcam.hal3a.v3.lsctbl.50 \
    libcam.hal3a.v3.nvram.50 \
    libcam.hal3a.v3.platform \
    libcam.hal3a.v3.resultpool \
    libcam.hal3a.v3 \
    libcam.halisp.buf \
    libcam.halisp.common \
    libcam.halisp \
    libcam.halsensor.hwintegration \
    libcam.halsensor \
    libcam.iopipe \
    libcam.isptuning \
    libcam.pdtblgen \
    libcam.seninfn3d \
    libcam.tuning.cache \
    libcam.utils.sensorprovider \
    libcam.vhdr \
    libcamalgo.3dnr \
    libcamalgo.aibc \
    libcamalgo.aidepth \
    libcamalgo.aihdr \
    libcamalgo.ainr \
    libcamalgo.dngop \
    libcamalgo.eis \
    libcamalgo.fdft \
    libcamalgo.fsc \
    libcamalgo.gyro \
    libcamalgo.ispfeature \
    libcamalgo.lmv \
    libcamalgo.lsc \
    libcamalgo.mfnr \
    libcamalgo.n3d \
    libcamalgo.nr \
    libcamalgo.platform \
    libcamalgo.platform2 \
    libcamalgo.rotate \
    libcamalgo.utility \
    libcamalgo.vaidepth \
    libcamalgo.vsf \
    libcamalgo.warp \
    libcamdrv_imem \
    libcamdrv_isp \
    libcamdrv_tuning_mgr \
    libcamdrv_twin \
    libcamera_scene \
    libcameracustom.eis \
    libcameracustom \
    libcom.xiaomi.pluginutils \
    libdip_drv \
    libdip_imem \
    libdip_postproc \
    libdualcam_optical_zoom_control \
    libdualcam_video_optical_zoom \
    libeffecthal.base \
    libfeature.face \
    libfeature.stereo.provider \
    libfeature.vsdof.hal \
    libfeature_3dnr \
    libfeature_eis \
    libfeature_fsc \
    libfeature_lmv \
    libfeature_rss \
    libfeatureiodrv_mem \
    libfocus \
    libheichal \
    libimagebuffer_wrapper \
    libimageio \
    libimageio_plat_drv \
    libimageio_plat_pipe \
    liblpcnr \
    libmfllcore \
    libmiai_deblur \
    libmiai_portraitsupernight \
    libmialgo_ie_capture \
    libmialgo_sd \
    libmialgo_utils \
    libmialgo_video_enhance \
    libmialgoengine \
    libmialgoengine2 \
    libmibokeh_845_video \
    libmibokeh_mt6873 \
    libmpbase \
    libmsnr \
    libmtkcam.atmseventmgr \
    libmtkcam.eventcallback \
    libmtkcam.featurepipe.capture \
    libmtkcam.featurepipe.depthmap \
    libmtkcam.featurepipe.streaming \
    libmtkcam.featurepipe.vsdof_util \
    libmtkcam.logicalmodule \
    libmtkcam_3rdcalibration \
    libmtkcam_3rdparty.arc.common \
    libmtkcam_3rdparty.arc.sat.wrapper \
    libmtkcam_3rdparty.core \
    libmtkcam_3rdparty.customer \
    libmtkcam_3rdparty.mtk \
    libmtkcam_3rdparty \
    libmtkcam_calibration_convertor \
    libmtkcam_calibration_provider \
    libmtkcam_cameraplatforminfoxiaomi \
    libmtkcam_debugutils \
    libmtkcam_device3_app \
    libmtkcam_device3_hal \
    libmtkcam_device3_hidl \
    libmtkcam_device3_hidlutils \
    libmtkcam_device3_utils \
    libmtkcam_devicesessionpolicy \
    libmtkcam_diputils \
    libmtkcam_exif \
    libmtkcam_fdvt \
    libmtkcam_featurepolicy \
    libmtkcam_featureutils \
    libmtkcam_fwkutils \
    libmtkcam_grallocutils \
    libmtkcam_hwnode \
    libmtkcam_hwutils \
    libmtkcam_imgbuf \
    libmtkcam_mapping_mgr \
    libmtkcam_metadata \
    libmtkcam_metastore \
    libmtkcam_mfb \
    libmtkcam_modulefactory_aaa \
    libmtkcam_modulefactory_custom \
    libmtkcam_modulefactory_drv \
    libmtkcam_modulefactory_utils \
    libmtkcam_modulehelper \
    libmtkcam_owe \
    libmtkcam_pipeline \
    libmtkcam_pipeline_fbm \
    libmtkcam_pipelinemodel \
    libmtkcam_pipelinemodel_adapter \
    libmtkcam_pipelinemodel_capture \
    libmtkcam_pipelinemodel_isp \
    libmtkcam_pipelinemodel_session \
    libmtkcam_pipelinemodel_utils \
    libmtkcam_pipelinemodel_zsl \
    libmtkcam_pipelinepolicy-aov \
    libmtkcam_pipelinepolicy-security \
    libmtkcam_pipelinepolicy-smvr \
    libmtkcam_pipelinepolicy \
    libmtkcam_pipelinepolicy_factory \
    libmtkcam_prerelease \
    libmtkcam_rsc \
    libmtkcam_scenariorecorder \
    libmtkcam_stdutils \
    libmtkcam_streamutils \
    libmtkcam_synchelper \
    libmtkcam_sysutils \
    libmtkcam_tuning_utils \
    libmtkcam_ulog \
    libmtkcam_vsync_util \
    libmtkisp_metadata \
    librelight_only \
    libsdk_sr \
    libstereoinfoaccessor_vsdof \
    libvideofilter_only \
    libvidhance \
    libvidhance_active_ois \
    libvidhance_autozoom \
    libvidhance_calibration_tool \
    libvidhance_face_stabilizer \
    libvidhance_horizon_correction \
    libvidhance_ldc \
    libvidhance_stabilizer \
    libvidhance_super_stabilization \
    libwa_opticalzoom_fusion \
    libxmi_high_dynamic_range \
    libmtkcam_streaminfo_plugin-p1stt \
    ov16a1qofilm_mipi_raw_IdxMgr \
    ov16a1qofilm_mipi_raw_tuning \
    ov64b40sunny_mipi_raw_1_IdxMgr \
    ov64b40sunny_mipi_raw_1_tuning \
    ov64b40sunny_mipi_raw_2_IdxMgr \
    ov64b40sunny_mipi_raw_2_tuning \
    ov64b40sunny_mipi_raw_IdxMgr \
    ov64b40sunny_mipi_raw_tuning \
    vendor.mediatek.hardware.camera.atms@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.1 \
    vendor.mediatek.hardware.camera.device@3.7 \
    vendor.mediatek.hardware.camera.frhandler@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.0 \
    vendor.mediatek.hardware.camera.lomoeffect@1.0 \
    vendor.mediatek.hardware.camera.postproc@1.0 \
    vendor.mediatek.hardware.camera.security@1.0 \
    batterysecret \
    camerahalserver \
    lib3a.ccu.ddr \
    lib3a.ccu.dm \
    lib3a.ccu.pm \
    mi_thermald
